version: 2
jobs:
  build-web:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo/lunch-web
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: npm-cache-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: npm-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Build App
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - lunch-web/build
workflows:
  version: 2
  build_deploy:
    jobs:
      - build-web
